[package]
name = "rust_lisp_interpreter"
version = "0.1.0"
authors = ["Scott Silver <silversh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"